---
#docker compose -f .\ai-gateway-docker-compose.yml up
version: '1.0'
services:
  ai_gate:
    command:
    # docker build -t ai_gate_img -f ./ai_gate_Dockerfile .
    image: ai_gate_img
    ports:
    - 5000:5000
    volumes:
    - "./models:/app/models"
    - "./embed_model:/app/embed_model"
    - "./nltk_data:/root/nltk_data"
    - "./output:/var/log/ai_gate"
    - "./DBs:/app/DB"
    - "./SOURCE_DOCUMENTS:/app/SOURCE_DOCUMENTS"
    restart: on-failure:0
    #command: sh -c "while true; do echo hello; sleep 2; done"
    command: sh -c "python -m flask run --host=0.0.0.0"
    environment:
    - FLASK_RUN_HOST=0.0.0.0
    - OUTPUT_DIR=/var/log/ai_gate/
    - PORT=5000
    - DEVICE=cpu

  ai_client:
    command:
    # docker build -t ai_client_img -f ./ai_client_Dockerfile .
    image: ai_client_img
    depends_on:
    - ai_gate
    volumes:
    - "C:/Users/markm/OneDrive/Desktop/container_apps/Thoth-KE-0.0.1/output:/var/log/ai_client"
    restart: on-failure:0
    command: sh -c "python setup_client.py"
    environment:
    - OUTPUT_DIR=/var/log/ai_client/
    - PORT=5000
    - AI_GATEWAY=ai_gate
...