---
#docker compose -f .\ai-gateway-docker-compose.yml up
version: '1.0'
services:
  ai_gate:
    command:
    # docker build -t ai_gate_img -f ./ai_gate_Dockerfile .
    image: ai_gate_img
    ports:
    - 5000:5000
    volumes:
    - "./workspace:/app/workspace"
    restart: on-failure:0
    #command: sh -c "while true; do echo hello; sleep 2; done"
    command: sh -c "python -m flask run --host=0.0.0.0"
    environment:
    - FLASK_RUN_HOST=0.0.0.0
    - OUTPUT_DIR=/app/workspace/output
    - PORT=5000
    - DEVICE=cpu
  doc_handler:
    command:
    # doc_handler_service
    # docker build -t doc_handler_img .
    image: doc_handler_img
    ports:
    - 5006:5006
    volumes:
    - "./workspace:/app/workspace"
    restart: on-failure:0
    command: sh -c "python -m flask run --host=0.0.0.0"
    environment:
    - FLASK_RUN_HOST=0.0.0.0
    - OUTPUT_DIR=/app/workspace/output
    - PORT=5006
  # ai_client:
  #   command:
  #   # docker build -t ai_client_img -f ./ai_client_Dockerfile .
  #   image: ai_client_img
  #   depends_on:
  #   - ai_gate
  #   volumes:
  #   - "./workspace:/var/log/ai_client"
  #   restart: on-failure:0
  #   command: sh -c "python setup_client.py"
  #   environment:
  #   - OUTPUT_DIR=/var/log/ai_client/
  #   - PORT=5000
  #   - AI_GATEWAY=ai_gate
...